all: presentation clean
    
presentation: gradle.tex
	lualatex gradle.tex
	lualatex gradle.tex
preso:	presentation 
clean: 
	rm gradle.aux gradle.toc gradle.log gradle.nav gradle.out gradle.run.xml gradle.bcf gradle.snm gradle.vrb
